#!/usr/bin/env python3
"""Generate src/util/cp932_table.h — a compact CP932 <-> Unicode table.

CP932 (Microsoft Shift_JIS) maps single bytes and (lead, trail) pairs to BMP
code points. The compat engine uses it only to match pack entry names between
UTF-8 script paths and Shift_JIS container names, so a static table is enough.

Run from the repository root:  python3 tools/gen_cp932_table.py
"""
import os
import sys

OUT = os.path.join(os.path.dirname(__file__), "..", "src", "util", "cp932_table.h")


def single_bytes():
    table = [0] * 256
    for b in range(256):
        try:
            cp = ord(bytes([b]).decode("cp932"))
        except Exception:
            continue
        if cp != 0xFFFD:
            table[b] = cp
    return table


def double_bytes():
    pairs = []
    leads = list(range(0x81, 0xA0)) + list(range(0xE0, 0xFD))
    trails = list(range(0x40, 0x7F)) + list(range(0x80, 0xFD))
    for lead in leads:
        for trail in trails:
            try:
                cp = ord(bytes([lead, trail]).decode("cp932"))
            except Exception:
                continue
            if cp == 0xFFFD:
                continue
            pairs.append((lead | (trail << 8), cp))
    pairs.sort()
    return pairs


def main():
    singles = single_bytes()
    pairs = double_bytes()
    lines = []
    lines.append("// Generated by tools/gen_cp932_table.py. Do not edit by hand.")
    lines.append("#pragma once")
    lines.append("#include <cstdint>")
    lines.append("")
    lines.append("namespace artc {")
    lines.append("")
    lines.append("// CP932 single-byte -> Unicode (0 = no mapping).")
    lines.append("static const uint16_t kCp932Single[256] = {")
    for i in range(0, 256, 8):
        row = ", ".join("0x%04x" % v for v in singles[i:i + 8])
        lines.append("    " + row + ",")
    lines.append("};")
    lines.append("")
    lines.append("// CP932 double-byte -> Unicode; code = lead | (trail << 8).")
    lines.append("struct Cp932Pair { uint16_t code; uint16_t uni; };")
    lines.append("static const Cp932Pair kCp932Pairs[] = {")
    for i in range(0, len(pairs), 6):
        row = ", ".join("{0x%04x,0x%04x}" % p for p in pairs[i:i + 6])
        lines.append("    " + row + ",")
    lines.append("};")
    lines.append("static const unsigned kCp932PairCount = sizeof(kCp932Pairs) / sizeof(kCp932Pairs[0]);")
    lines.append("")
    lines.append("} // namespace artc")
    lines.append("")

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    sys.stderr.write("wrote %s: %d single, %d pairs\n" % (OUT, len(singles), len(pairs)))


if __name__ == "__main__":
    main()
