# Platform libraries belong to the core's link interface, including when no
# standalone JNI/Activity host is built by an embedded consumer.
set(ARTC_GRAPHICS_BACKEND AUTO CACHE STRING "Renderer: AUTO, HEADLESS, GLES or DESKTOP_GL")
set_property(CACHE ARTC_GRAPHICS_BACKEND PROPERTY STRINGS AUTO HEADLESS GLES DESKTOP_GL)
set(ARTC_AUDIO_BACKEND AUTO CACHE STRING "Audio: AUTO, OPENSL, OHAUDIO or NULL")
set_property(CACHE ARTC_AUDIO_BACKEND PROPERTY STRINGS AUTO OPENSL OHAUDIO NULL)
set(ARTC_GLES_TARGET "" CACHE STRING "Existing target providing matching EGL/GLES libraries and headers")
string(TOUPPER "${ARTC_GRAPHICS_BACKEND}" _artc_graphics)
string(TOUPPER "${ARTC_AUDIO_BACKEND}" _artc_audio)
if(_artc_graphics STREQUAL "AUTO")
    if(ANDROID OR OHOS OR CMAKE_SYSTEM_NAME STREQUAL "iOS" OR ARTC_TEST_GLES)
        set(_artc_graphics GLES)
    else()
        set(_artc_graphics HEADLESS)
    endif()
endif()
if(_artc_audio STREQUAL "AUTO")
    if(ANDROID)
        set(_artc_audio OPENSL)
    elseif(OHOS)
        set(_artc_audio OHAUDIO)
    elseif(CMAKE_SYSTEM_NAME STREQUAL "iOS")
        message(FATAL_ERROR "Apple audio is not implemented. Select NULL explicitly for compile-only validation.")
    else()
        set(_artc_audio NULL)
    endif()
endif()

add_library(artemis_platform INTERFACE)
if(_artc_graphics STREQUAL "GLES")
    target_compile_definitions(artemis_platform INTERFACE ARTC_HAS_GLES=1)
    if(ARTC_GLES_TARGET)
        if(NOT TARGET "${ARTC_GLES_TARGET}")
            message(FATAL_ERROR "ARTC_GLES_TARGET must name an existing CMake target")
        endif()
        target_link_libraries(artemis_platform INTERFACE "${ARTC_GLES_TARGET}")
    elseif(ANDROID OR OHOS)
        target_link_libraries(artemis_platform INTERFACE EGL GLESv2)
    else()
        find_package(unofficial-angle CONFIG REQUIRED)
        find_path(ARTC_GLES_INCLUDE_DIR GLES2/gl2.h REQUIRED)
        find_path(ARTC_EGL_INCLUDE_DIR EGL/egl.h REQUIRED)
        target_include_directories(artemis_platform INTERFACE
            "${ARTC_GLES_INCLUDE_DIR}" "${ARTC_EGL_INCLUDE_DIR}")
        target_link_libraries(artemis_platform INTERFACE
            unofficial::angle::libEGL unofficial::angle::libGLESv2)
    endif()
elseif(_artc_graphics STREQUAL "DESKTOP_GL")
    if(NOT CMAKE_SYSTEM_NAME STREQUAL "Darwin")
        message(FATAL_ERROR "DESKTOP_GL is only supported by the macOS host")
    endif()
    target_compile_definitions(artemis_platform INTERFACE ARTC_HAS_GLES=1 ARTC_USE_DESKTOP_GL=1)
    target_link_libraries(artemis_platform INTERFACE "-framework OpenGL")
elseif(NOT _artc_graphics STREQUAL "HEADLESS")
    message(FATAL_ERROR "Unknown ARTC_GRAPHICS_BACKEND: ${ARTC_GRAPHICS_BACKEND}")
endif()

if(_artc_audio STREQUAL "OPENSL")
    if(NOT ANDROID)
        message(FATAL_ERROR "OPENSL requires an Android toolchain")
    endif()
    target_compile_definitions(artemis_platform INTERFACE ARTC_AUDIO_OPENSL=1)
    target_link_libraries(artemis_platform INTERFACE OpenSLES)
elseif(_artc_audio STREQUAL "OHAUDIO")
    if(NOT OHOS)
        message(FATAL_ERROR "OHAUDIO requires an OpenHarmony toolchain")
    endif()
    target_link_libraries(artemis_platform INTERFACE ohaudio)
elseif(NOT _artc_audio STREQUAL "NULL")
    message(FATAL_ERROR "Unknown ARTC_AUDIO_BACKEND: ${ARTC_AUDIO_BACKEND}")
endif()
if(ANDROID)
    target_link_libraries(artemis_platform INTERFACE log android)
elseif(OHOS)
    target_link_libraries(artemis_platform INTERFACE hilog_ndk.z)
endif()
if(ARTC_BUILD_JNI AND (NOT ANDROID OR NOT _artc_graphics STREQUAL "GLES" OR NOT _artc_audio STREQUAL "OPENSL"))
    message(FATAL_ERROR "The official Android host requires Android, GLES and OPENSL")
endif()
if(ARTC_TEST_GLES AND NOT _artc_graphics STREQUAL "GLES")
    message(FATAL_ERROR "ARTC_TEST_GLES requires the GLES backend")
endif()
message(STATUS "Artemis backends: graphics=${_artc_graphics}, audio=${_artc_audio}")
